task4.5.1
pogorelets/places pull request #12
Opened 2020-12-14 19:46 UTC by pogorelets

![image](https://user-images.githubusercontent.com/18634975/102127959-36abaa80-3e5e-11eb-91de-03872a900d0a.png)

2020-12-15 08:38 UTC, pretorean commented on lib/ui/screen/sight_card.dart
> +                Center(child: CircularProgressIndicator()),
Этот виджет тут лишний

2020-12-15 08:53 UTC, pretorean requested changes

2020-12-15 08:53 UTC, pretorean commented on lib/ui/screen/sight_card.dart
>                        topRight: Radius.circular(radiusImage),
Во второй части карточки, где текст, нужно сделать тоже скругление углов, чтобы было как в дизайне.

```
decoration: BoxDecoration(
                color: bkgCardSightColor,
                borderRadius: BorderRadius.only(
                  bottomLeft: Radius.circular(radiusImage),
                  bottomRight: Radius.circular(radiusImage),
                ),
              ),
```

2020-12-15 09:12 UTC, pretorean commented on lib/ui/screen/sight_card.dart
> +                Center(child: CircularProgressIndicator()),
Этот виджет будет отображаться всегда, даже если его не видно под картинкой, и вызывать постоянную перерисовку экрана.
Попробуйте отобразить картинку как виджет:
```
Image.network(
                    sight.url,
                    loadingBuilder: (context, child, progress) {
                      if (progress == null)
                        return child;
                      else
                        return CircularProgressIndicator();
                    },
                  )```

это позволит отображать лоадер только когда картинка еще не загрузилась, а после загрузки картинки лоадер исчезнет из дерева виджетов

2020-12-16 15:12 UTC, pogorelets commented on lib/ui/screen/sight_card.dart
>                        topRight: Radius.circular(radiusImage),
исправлено
![image](https://user-images.githubusercontent.com/18634975/102366961-46480200-3fca-11eb-8731-0c97fb26d94e.png)

2020-12-17 06:25 UTC, Jokerkras approved these changes

2020-12-17 18:03 UTC, merged